name: Weekly Test

on:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - name: Check isort
        run: pipenv run isort --recursive --diff .

      - name: Check isort
        run: pipenv run black --check .

      - name: Check flake8
        run: pipenv run flake8

      - name: Check mypy
        run: pipenv run mypy

      - name: Check pytest
        run: pipenv run pytest --cov --cov-fail-under=90 --cov-report xml

      - name: Scraper testing
        run: |
          pipenv run fetch-allocine --number_of_pages 1 --from_page 1 --output_csv_name allocine_movies.csv
          read -r num < diff.txt
          if [[ "$num" -gt 3 ]]; then
            echo "Test failed!"
            exit 1
          else
            echo "Test succeeded!"
            exit 0
          fi
