  name: Test

  on:
    pull_request: {}
    push:
      branches:
        - master
      tags:
        - "*"

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v5
        
        - name: "Set up Python"
          uses: actions/setup-python@v5
          with:
            python-version-file: ".python-version"

        - name: Install dependencies with uv
          run: uv sync --all-extras --dev

        - name: Check ruff
          run: uv run ruff check .

        - name: Check ruff format
          run: uv run ruff format --check .

        - name: Check mypy
          run: uv run mypy

        - name: Check pytest
          run: uv run pytest --cov --cov-fail-under=90 --cov-report xml
